[VL] Database: JDBC
Programmiermethoden-CampusMinden/PM-Lecture pull request #327
Opened 2022-03-17 14:11 UTC by AMatutat

- [x] Abbildung Zeichnen
- [x] Inhalt
    - [x] Eigentlicher Inhalt
    - [ ] Tldr
    - [ ] Wrap-Up
- [ ] Formatierung
- [ ] meta daten
- [ ] Code testen/prüfen ob noch up-to-date
- [ ] Video (@cagix)
- [ ] Link zum Quiz

2022-03-21 15:16 UTC, AMatutat commented
@cagix Inhaltlich habe ich jetzt alles drinnen, was ich drinnen haben möchte. Ein erstes Feedback wäre gut.
Formatierung etc. muss ich noch anpassen.
Muss den ganzen Spaß auch nochmal testen. Hab zwar verschiedene Dokus zur Hand genommen, aber sich ist sicher. 
Grundsätzlich habe ich in den Codebeispielen das ExceptionHandling weggelassen, einfach um die Lesbarkeit beizubehalten. 

Themen, die es NICHT reingeschafft haben:
- Typen von Treibern
- `CallableStatements` damit ruft man, auf der Datenbank vorher konfigurierte, Befehle auf. Ist nicht sonderlich komplex (daher gut im Selbststudium), aber ich glaube, die machen auch in DB nichts damit. Deswegen mal weggelassen.
- Beispiele für "komplexeres" `ResultSet` Handling. Mit `ResultSet#next` scheint man 99% der Anwendungsfälle abzudecken. Beim Rest habe ich beschrieben, wie man das konfiguriert, aber nicht wie man das anwendet. Da reicht ein Blick in die Javadoc. Das ist alles recht stumpf (`#first`,`#last` etc.)
- `DataStreams` (Das könnte tatsächlich noch ganz Interessant sein)
- Und dann natürlich alles was sehr spezifisch/nichisch ist.

2022-03-21 18:29 UTC, cagix requested changes
gefällt!

zwei punkte: 

- [x] bild anpassen (siehe screenshot)
- [ ] gibt es ne in-memory-db, die bei java/open-jdk evtl. schon dabei ist, damit man den spass ohen extra db-installation demonstrieren kann?

<img width="676" alt="Screenshot 2022-03-21 at 19 25 27" src="https://user-images.githubusercontent.com/20356276/159339953-110bc891-4fb8-4510-ae10-fc440666d374.png">

2022-03-22 05:53 UTC, cagix commented
@AMatutat Mach mal hier noch die beiden Dinge aus dem Review fertig, so lange Du noch im Thema bist. Danach legen wir das erstmal zur Seite: Kollege B. hat sich gemeldet und meint, das wäre von Anfang an für in x Jahren gedacht gewesen. Kommunikation 🤷🤣

2022-03-22 11:59 UTC, AMatutat commented
> gibt es ne in-memory-db, die bei java/open-jdk evtl. schon dabei ist, damit man den spass ohen extra db-installation demonstrieren kann?

Also eine mitgelieferte DB gibt es nicht. 
Ich glaube [SQLite](https://www.sqlite.org/index.html) ist das "geringste" übel.

2022-03-22 12:42 UTC, cagix commented
> > gibt es ne in-memory-db, die bei java/open-jdk evtl. schon dabei ist, damit man den spass ohen extra db-installation demonstrieren kann?
> 
> 
> 
> Also eine mitgelieferte DB gibt es nicht. 
> 
> Ich glaube [SQLite](https://www.sqlite.org/index.html) ist das "geringste" übel. 

mift. na gut, dann lassen wir das erstmal liegen (bis auf die abbildung)

2022-03-22 13:20 UTC, cagix reviewed
👍 Bild passt jetzt, und den Feinschliff muss man dann später machen

2024-01-27 13:38 UTC, cagix approved these changes
@AMatutat Ich merge hier mal. 

Das Material ist zwar noch gaaaaanz weit weg von "fertig" und braucht noch richtig viel Hinwendung. 

Aber ich muss die Strukturen im Repo überarbeiten für das aktuelle Tooling, und danach würde dieser PR gar nicht mehr passen. Damit das nicht verloren geht, merge ich jetzt besser mal.

2024-01-27 13:38 UTC, merged